# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 08:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yiliquanlu', '0003_auto_20160815_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RenameField(
            model_name='uploadtext',
            old_name='content',
            new_name='news_content',
        ),
        migrations.AddField(
            model_name='uploadtext',
            name='news_time',
            field=models.DateField(default='2016-07-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadtext',
            name='news_title',
            field=models.CharField(default='title', max_length=30),
            preserve_default=False,
        ),
    ]
